'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace WebApplicationDGM

    Partial Public Class Database1Entities
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=Database1Entities")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property TB_CLIENTE() As DbSet(Of TB_CLIENTE)
        Public Overridable Property TB_TIPO_CLIENTE() As DbSet(Of TB_TIPO_CLIENTE)
        Public Overridable Property Views() As DbSet(Of View)
    
    End Class

End Namespace
