'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace WebApplicationDGM

    Partial Public Class TB_CLIENTE
        Public Property COD_CLIENTE As Integer
        Public Property NOM_USUAL As String
        Public Property NOM_COMPLETO As String
        Public Property NRO_CPF As Nullable(Of Decimal)
        Public Property DT_EXCLUIDO As Nullable(Of Date)
        Public Property COD_TIPO_CLIENTE As Nullable(Of Integer)
    
        Public Overridable Property TB_TIPO_CLIENTE As TB_TIPO_CLIENTE
    
    End Class

End Namespace
