'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace WebApplicationDGM

    Partial Public Class TB_TIPO_CLIENTE
        Public Property COD_TIPO_CLIENTE As Integer
        Public Property DSC_TIPO_CLIENTE As String
        Public Property DT_EXCLUIDO As Nullable(Of Date)
    
        Public Overridable Property TB_CLIENTE As ICollection(Of TB_CLIENTE) = New HashSet(Of TB_CLIENTE)
    
    End Class

End Namespace
