'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace WebApplicationDGM

    Partial Public Class View
        Public Property COD_CLIENTE As Integer
        Public Property NOM_COMPLETO As String
        Public Property NOM_USUAL As String
        Public Property NRO_CPF As Nullable(Of Decimal)
        Public Property DSC_TIPO_CLIENTE As String
    
    End Class

End Namespace
